# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstCitizen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher', '~> 5.0'
  pod 'SnapKit'
  pod 'naveridlogin-sdk-ios'
  pod 'NMapsMap'
  # Pods for FirstCitizen

end
